// Code generated by cmd/reset. DO NOT EDIT.

package repository

// Reset сбрасывает состояние URLRecord к нулевым значениям.
// Сгенерировано утилитой cmd/reset по директиве // generate:reset.
func (rs *URLRecord) Reset() {
	if rs == nil {
		return
	}
	rs.UUID = ""
	rs.ShortURL = ""
	rs.OriginalURL = ""
	rs.UserID = ""
	rs.DeletedFlag = false
}
