package main

import (
	"errors"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// writeGoFile создаёт Go-файл name в директории dir с содержимым src.
func writeGoFile(t *testing.T, dir, name, src string) {
	t.Helper()
	path := filepath.Join(dir, name)
	require.NoError(t, os.WriteFile(path, []byte(src), 0o644))
}

// readGenerated читает содержимое сгенерированного файла reset.gen.go.
func readGenerated(t *testing.T, dir string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(dir, generatedFileName))
	require.NoError(t, err)
	return string(data)
}

// TestFindResetStructs проверяет поиск структур с директивой // generate:reset.
func TestFindResetStructs(t *testing.T) {
	dir := t.TempDir()
	writeGoFile(t, dir, "a.go", `package a

// generate:reset
type Resetable struct {
	N    int
	Name string
}

type Plain struct {
	X int
}
`)

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filepath.Join(dir, "a.go"), nil, parser.ParseComments)
	require.NoError(t, err)

	pkg := newPkgInfo()
	collectFile(f, pkg)

	// Найдена только структура с директивой
	require.Len(t, pkg.directed, 1)
	assert.Equal(t, "Resetable", pkg.directed[0].name)
	assert.Len(t, pkg.directed[0].fields, 2)
	assert.Equal(t, "N", pkg.directed[0].fields[0].name)
	assert.Equal(t, "Name", pkg.directed[0].fields[1].name)

	// Обе структуры известны как локальные, но директива — у одной
	assert.Contains(t, pkg.structs, "Plain")
	assert.True(t, pkg.hasReset["Resetable"])
	assert.False(t, pkg.hasReset["Plain"])
}

// TestDirectiveMentionInDocNotMatched проверяет, что упоминание директивы
// в тексте godoc не считается директивой генерации.
func TestDirectiveMentionInDocNotMatched(t *testing.T) {
	dir := t.TempDir()
	writeGoFile(t, dir, "a.go", `package a

// Documented — структура, в чьём godoc лишь упоминается
// директива // generate:reset, но не как отдельная строка.
type Documented struct {
	X int
}
`)

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filepath.Join(dir, "a.go"), nil, parser.ParseComments)
	require.NoError(t, err)

	pkg := newPkgInfo()
	collectFile(f, pkg)
	assert.Empty(t, pkg.directed, "упоминание в тексте godoc не должно считаться директивой")
}

// TestGenerateResetMethod проверяет генерацию метода Reset для структуры
// со всеми основными видами полей.
func TestGenerateResetMethod(t *testing.T) {
	dir := t.TempDir()
	writeGoFile(t, dir, "a.go", `package a

// generate:reset
type ResetableStruct struct {
	i     int
	str   string
	strP  *string
	s     []int
	m     map[string]string
	child *ResetableStruct
}
`)

	n, err := generateForDir(dir)
	require.NoError(t, err)
	assert.Equal(t, 1, n)

	code := readGenerated(t, dir)

	// Заголовок сгенерированного файла
	assert.True(t, len(code) > 0 &&
		code[:len("// Code generated by cmd/reset. DO NOT EDIT.")] == "// Code generated by cmd/reset. DO NOT EDIT.",
		"файл должен начинаться с заголовка генерации")
	assert.Contains(t, code, "package a")

	// Метод и все операторы сброса
	assert.Contains(t, code, "func (rs *ResetableStruct) Reset() {")
	assert.Contains(t, code, "if rs == nil {\n\t\treturn\n\t}")
	assert.Contains(t, code, "rs.i = 0")
	assert.Contains(t, code, `rs.str = ""`)
	assert.Contains(t, code, "if rs.strP != nil {")
	assert.Contains(t, code, `*rs.strP = ""`)
	assert.Contains(t, code, "rs.s = rs.s[:0]")
	assert.Contains(t, code, "clear(rs.m)")
	assert.Contains(t, code, "if rs.child != nil {")
	assert.Contains(t, code, "rs.child.Reset()")

	// Сгенерированный код должен быть синтаксически корректным
	_, err = parser.ParseFile(token.NewFileSet(), filepath.Join(dir, generatedFileName), nil, 0)
	assert.NoError(t, err)
}

// TestGenerateNestedAndSpecialTypes проверяет вложенные структуры,
// интерфейсы, каналы и функции.
func TestGenerateNestedAndSpecialTypes(t *testing.T) {
	dir := t.TempDir()
	writeGoFile(t, dir, "a.go", `package a

type Inner struct {
	V int
}

type WithReset struct {
	Z int
}

func (w *WithReset) Reset() { w.Z = 0 }

type NoReset struct {
	Q string
}

// generate:reset
type Outer struct {
	in    Inner
	w     *WithReset
	p     *NoReset
	iface interface{ Do() }
	ch    chan int
	fn    func()
}
`)

	n, err := generateForDir(dir)
	require.NoError(t, err)
	assert.Equal(t, 1, n)

	code := readGenerated(t, dir)

	// Value-структура без Reset — рекурсивный сброс полей
	assert.Contains(t, code, "rs.in.V = 0")

	// Указатель на структуру с Reset — вызов метода
	assert.Contains(t, code, "if rs.w != nil {")
	assert.Contains(t, code, "rs.w.Reset()")

	// Указатель на структуру без Reset — рекурсивный сброс полей
	assert.Contains(t, code, "if rs.p != nil {")
	assert.Contains(t, code, `rs.p.Q = ""`)

	// Интерфейс — type assertion на interface{ Reset() }
	assert.Contains(t, code, "if resetter, ok := rs.iface.(interface{ Reset() }); ok {")
	assert.Contains(t, code, "resetter.Reset()")

	// Канал и функция не сбрасываются
	assert.Contains(t, code, "// rs.ch: канал не сбрасывается")
	assert.Contains(t, code, "// rs.fn: функция не сбрасывается")
}

// TestNoDirectiveNoFile проверяет, что без директив файл reset.gen.go
// не создаётся.
func TestNoDirectiveNoFile(t *testing.T) {
	dir := t.TempDir()
	writeGoFile(t, dir, "b.go", `package b

type Plain struct {
	X int
}
`)

	n, err := generateForDir(dir)
	require.NoError(t, err)
	assert.Equal(t, 0, n)

	_, err = os.Stat(filepath.Join(dir, generatedFileName))
	assert.True(t, errors.Is(err, os.ErrNotExist), "файл reset.gen.go не должен создаваться")
}

// TestStaleFileRemoved проверяет удаление устаревшего reset.gen.go
// в пакете без директив.
func TestStaleFileRemoved(t *testing.T) {
	dir := t.TempDir()
	writeGoFile(t, dir, "b.go", "package b\n\ntype Plain struct{ X int }\n")
	writeGoFile(t, dir, generatedFileName, "// Code generated by cmd/reset. DO NOT EDIT.\n\npackage b\n")

	n, err := generateForDir(dir)
	require.NoError(t, err)
	assert.Equal(t, 0, n)

	_, err = os.Stat(filepath.Join(dir, generatedFileName))
	assert.True(t, errors.Is(err, os.ErrNotExist), "устаревший файл должен быть удалён")
}

// TestRunRecursive проверяет рекурсивный обход директорий из корня.
func TestRunRecursive(t *testing.T) {
	root := t.TempDir()
	sub := filepath.Join(root, "sub", "pkg")
	require.NoError(t, os.MkdirAll(sub, 0o755))
	writeGoFile(t, sub, "c.go", `package c

// generate:reset
type R struct {
	N int
}
`)

	require.NoError(t, run(root))

	code := readGenerated(t, sub)
	assert.Contains(t, code, "package c")
	assert.Contains(t, code, "func (rs *R) Reset() {")
	assert.Contains(t, code, "rs.N = 0")
}

// TestZeroValue проверяет литералы нулевых значений примитивных типов.
func TestZeroValue(t *testing.T) {
	tests := []struct {
		name string
		want string
		ok   bool
	}{
		{name: "int", want: "0", ok: true},
		{name: "int64", want: "0", ok: true},
		{name: "uint8", want: "0", ok: true},
		{name: "float64", want: "0", ok: true},
		{name: "byte", want: "0", ok: true},
		{name: "rune", want: "0", ok: true},
		{name: "string", want: `""`, ok: true},
		{name: "bool", want: "false", ok: true},
		{name: "any", want: "nil", ok: true},
		{name: "error", want: "nil", ok: true},
		{name: "MyType", ok: false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, ok := zeroValue(tt.name)
			assert.Equal(t, tt.ok, ok)
			if tt.ok {
				assert.Equal(t, tt.want, got)
			}
		})
	}
}

// TestSkipDir проверяет пропуск директорий при обходе.
func TestSkipDir(t *testing.T) {
	assert.True(t, skipDir(".git"))
	assert.True(t, skipDir(".idea"))
	assert.True(t, skipDir("vendor"))
	assert.True(t, skipDir("testdata"))
	assert.True(t, skipDir("node_modules"))
	assert.False(t, skipDir("internal"))
	assert.False(t, skipDir("cmd"))
}
