// Code generated by cmd/reset. DO NOT EDIT.

package worker

// Reset сбрасывает состояние DeleteTask к нулевым значениям.
// Сгенерировано утилитой cmd/reset по директиве // generate:reset.
func (rs *DeleteTask) Reset() {
	if rs == nil {
		return
	}
	rs.UserID = ""
	rs.ShortURL = ""
}
