// Code generated by cmd/reset. DO NOT EDIT.

package audit

// Reset сбрасывает состояние Event к нулевым значениям.
// Сгенерировано утилитой cmd/reset по директиве // generate:reset.
func (rs *Event) Reset() {
	if rs == nil {
		return
	}
	rs.TS = 0
	rs.Action = ""
	rs.UserID = ""
	rs.URL = ""
}
